apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_DB: your-db-here
  POSTGRES_USER: your-username-here
  POSTGRES_PASSWORD: your-password-here
  DATABASE_URL: postgresql://YOUR_USER:YOUR_PASSWORD@postgres-service:5432/YOUR_DB

