apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: flask-api
type: Opaque
stringData:
  POSTGRES_DB: <your-db-name>
  POSTGRES_USER: <your-rds-username>
  POSTGRES_PASSWORD: <your-rds-password>
  DATABASE_URL: postgresql://<user>:<password>@<rds-endpoint>:5432/<db-name>
